---

# ==> Create new domain
- name: copy create domain python script
  template: src=create-domain.py dest={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}
  tags:
    - create-domain
- name: Execute create domain script
  shell: "{{ middleware_common_home }}/common/bin/wlst.sh {{ mw_installer_folder }}/create-domain.py > {{ oracle_base }}/logs/create_domain_{{ domain_name }}_$(date +'%F').log 2>&1"
  tags:
    - create-domain
- name: Update 'JAVA_OPTIONS' variable within startNodeManager script
  lineinfile:
    dest: "{{ domain_home }}/bin/startNodeManager.sh"
    regexp: '^JAVA_OPTIONS='
    line: 'JAVA_OPTIONS="${JAVA_OPTIONS} -Djava.security.egd=file:///dev/urandom -Dweblogic.RootDirectory=${DOMAIN_HOME}"'
- name: Add Oracle Home environment variables
  lineinfile: dest='/home/{{ oracle_user }}/.bashrc' line='export ORACLE_HOME={{ middleware_home }}'
  tags:
    - oracle-vars

- name: Copy 'setUserOverrides.sh' script
  template:
    src: setUserOverrides.sh
    dest: "{{ domain_home }}/bin/setUserOverrides.sh"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0750
  tags:
    - create-domain